# Generated by Django 6.0.1 on 2026-02-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UwsStaffManagement', '0003_manager_email_manager_first_name_manager_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='email',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='username',
        ),
        migrations.RemoveField(
            model_name='uwsadmin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='uwsadmin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='uwsadmin',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='uwsadmin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='uwsadmin',
            name='username',
        ),
    ]
