# Generated by Django 6.0.1 on 2026-02-03 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UwsStaffManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAdmin',
            fields=[
                ('ClientAdminId', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ClientAdminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientManagement.clientadmin')),
            ],
        ),
        migrations.CreateModel(
            name='ClientDivision',
            fields=[
                ('ClientDivisionId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ClientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientManagement.client')),
                ('DivisionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UwsStaffManagement.division')),
            ],
        ),
    ]
