# Generated by Django 6.0.1 on 2026-02-12 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ClientAdminId',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RenameModel(
            old_name='ClientAdmin',
            new_name='OrganisationAdmin',
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('ClientId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('ClientAdminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientManagement.organisationadmin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='clientdivision',
            name='ClientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientManagement.organisation'),
        ),
    ]
