# Generated by Django 6.0.1 on 2026-02-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientManagement', '0002_remove_client_clientadminid_remove_client_user_and_more'),
        ('EventManagement', '0002_alter_attendee_clientid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
