# Generated by Django 6.0.1 on 2026-02-03 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClientManagement', '0001_initial'),
        ('UwsStaffManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ManagerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UwsStaffManagement.manager')),
                ('UwsAdminId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UwsStaffManagement.uwsadmin')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UwsStaffManagement.division')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('AttendeeId', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('ClientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientManagement.client')),
                ('EventId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventManagement.event')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('NewsletterId', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('EventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManagement.event')),
            ],
        ),
    ]
