# Generated by Django 6.0.1 on 2026-02-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientManagement', '0002_remove_client_clientadminid_remove_client_user_and_more'),
        ('EventManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='ClientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientManagement.organisation'),
        ),
    ]
